# Generated by Django 6.0.4 on 2026-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author_chatmessage_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
